### ISSUE TITLE
WARNING: Multiple instances of some keys were found in the ObfuscationMap.

### ISSUE THREAD

**Issue by Gaffx** [ydkhatri/OneDrive#1]
Hi @ydkhatri,

Thanks for creating this great script. I have attempted to follow your guidance and test it out on OneDrive account (windows 10); however, I received the following warning and error messages: 

```
WARNING: Multiple instances of some keys were found in the ObfuscationMap.
Read 6494 items from map
Failed to create CSV file: ~/Desktop/odl_output.csv

```
Any advice that could assist me in parsing OneDrive logs?

Best

mzheader

**Comment by ydkhatri** [comment]
The Warning has nothing to do with the "Failed to create CSV.." error. You probably have the file locked (open in another editor perhaps). Check and try again.

**Comment by Gaffx** [comment]
Thank you! I've tried it out again on fresh vanilla Ubuntu image and it worked out. Now, I'm attempting to develop a better understanding of how to read these logs effectively. Perhaps I'll start digging for some clear text file names and their attributes and take it from there...

**Comment by ydkhatri** [comment]
There is now a new version that works with the latest OneDrive obfuscation. You would have missed those entries.
