### ISSUE TITLE
Python with error odl.py:2: SyntaxWarning: invalid escape sequence '\A' and missing Crypto library

### ISSUE THREAD

**Issue by Alexeijn** [ydkhatri/OneDrive#11]
Python is complaining about 2 things:
1) Invalid escape sequence \A
%userprofile%\Downloads\odl.py:2: SyntaxWarning: invalid escape sequence '\A'
  """

2) No lib Crypto
Traceback (most recent call last):
  File "%useprofile%\Downloads\odl.py", line 53, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'

I`using Oficial Python, not the Microsoft python in the store.
I`ve tested with Microsoft Store python version and the result is the same.

**Comment by Beercow** [comment]
Sounds like the dependencies are not met. Did you install construct and pycryptodome?

**Comment by Alexeijn** [comment]
Oh, my mistake, I didn`t installed pycryptodome.

But after doing it, the first error is shown as a SyntaxWarning:
%userprofile%\Downloads\odl.py:2: SyntaxWarning: invalid escape sequence '\A'
  """

**Comment by ydkhatri** [comment]
A requirements.txt file has now been added to specify the required modules. Also fixed the syntax warning for python 3.12
