### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by phoenixhcc** [ydkhatri/OneDrive#2]
Thank you so much for your python script :)

I am trying to use the script to parse the ODL logs under "Personal", but getting the following error message "did not find 0xCCDDEEFF". Is the ODL that I am using not compatible with the script?

ERROR writing rows: <class 'TypeError'> 'NoneType' object is not iterable
Searching  /home/user/Documents/7236_onedrive/logs/Personal/FileCoAuth-2022-09-04.0155.4976.1.odlgz
wrong header! Did not find 0xCCDDEEFF

**Comment by ydkhatri** [comment]
Can you send the file so I can debug?

**Comment by ydkhatri** [comment]
This should be fixed now in https://github.com/ydkhatri/OneDrive/commit/0370f1f61c29c4a5b104454434798e49c2d2740f
