### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by vegetableZucchini** [ydkhatri/OneDrive#5]
Thanks for your contribution of this tool unfortunately I get the following error when running it.

```
python3 odl.py -h
  File "odl.py", line 68
    return datetime.datetime(1970, 1, 1) + 
                                          ^
SyntaxError: invalid syntax
```

**Comment by Beercow** [comment]
Are you running this on Windows by chance? Try removing the first line and try it again. 
#!/usr/bin/env python3

**Comment by Beercow** [comment]
Or you could leave it in there and try 
python3 -x odl.py -h

**Comment by ydkhatri** [comment]
What version of python3 are you using? Have you (or some other tool/library) overwritten the default `datetime` library with something else?

**Comment by vegetableZucchini** [comment]
> Are you running this on Windows by chance? Try removing the first line and try it again. #!/usr/bin/env python3

on macOS

**Comment by vegetableZucchini** [comment]
> What version of python3 are you using? Have you (or some other tool/library) overwritten the default `datetime` library with something else?

3.8
Thanks for the tip I think this is the case.

**Comment by ydkhatri** [comment]
Closing for lack of further response.
