### ISSUE TITLE
"ObfuscationStringMap.txt" not found

### ISSUE THREAD

**Issue by Moiseskoper** [ydkhatri/OneDrive#7]
Receiving this error: 

"ObfuscationStringMap.txt" not found in C:\users\moises\Desktop\logsone.
Recovered Unobfuscation key xbdHp7zBHRYKgL1kElvMV367ShkuVyRKaxv0UGmkcN0=, version=1, utf_type=utf16
Failed to create csv file: ~/Desktop/odl_output.csv

I have the general.keystore file instead in the same directory.

**Comment by ydkhatri** [comment]
The output file. `~/Desktop/odl_output.csv` is probably just in use and locked. Try with a different output file name and path.

**Comment by ydkhatri** [comment]
Closing for lack of response.
