### ISSUE TITLE
csv Error need to escape, but no escapechar set

### ISSUE THREAD

**Issue by Dulani** [ydkhatri/OneDrive#8]
Thanks for this very useful tool!  I've got it working but am getting this error after each logfile: 
`ERROR writing rows: <class '_csv.Error'> need to escape, but no escapechar set`

Any suggestions for things I can change (or does something need to be changed in your script)?

Thanks in advance!

**Comment by ydkhatri** [comment]
Hi, what version of python are you using, and which platform/os version?

Also, can you submit a sample file that demonstrates the problem?

**Comment by Dulani** [comment]
Hi, thanks for your quick response.  I am using Python 3.10.5 and MacOS 12.7.  I'd be happy to share a sample via PM (if I can figure out how to do that on GH).

**Comment by ydkhatri** [comment]
Or send via email.

**Comment by ydkhatri** [comment]
Closing for lack of response.
